# Generated by Django 5.2.3 on 2025-07-03 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_newsarticle_video'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Video',
        ),
    ]
